name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "STLC_Project_Execution/Automation_Framework/package-lock.json"

      - name: Install dependencies
        run: |
          cd STLC_Project_Execution/Automation_Framework
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd STLC_Project_Execution/Automation_Framework
          npx playwright install chromium --with-deps

      - name: Run Playwright tests
        run: |
          cd STLC_Project_Execution/Automation_Framework
          npx playwright test --project=chromium

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: STLC_Project_Execution/Automation_Framework/playwright-report/
          retention-days: 30
